### ISSUE TITLE
Updater

### ISSUE THREAD

**Issue by janvanveldhuizen** [synt4x93/OTA#3]
Will the updater work when I install the version from this repo? 
I currently have LineageOS 18.1 that gives an error when checking for updates.
"The update check failed. Please check your internet connection and try later."

I took my current install from here: https://www.naldotech.com/download-lineageos-18-1-on-samsung-galaxy-s9-s9-how-to-install/

**Comment by synt4x93** [comment]
Yep will work fine
What device do you have?

Haha strange just saw your link, keep seeing my builds posted everywhere!
I think the 15/12/2020 build linked there, I didn't include ota if I remember correctly, so I'd guess that's why it fails for you.

**Comment by drimulescu** [comment]
Hello @synt4x93 
Will it also work if I have the NikGapps installed? The ones from 31.12
I saw some discussion over the XDA Thread and I saw that it will end in a boot loop unless I flash the NikGapps from 14.12.2020?
Is this issue still valid? 
Thanks

**Comment by synt4x93** [comment]
The 14/12/2020 core nikgapps package is what I suggest to use.

Nikgapps broke the /system/addon.d script in their 31/12/2020 build.
It works when flashing it in recovery.. but as soon as you reflash ROM or ota update it will bootloop as nikgapps doesn't restore itself correctly because of their broken script. You can either reflash 31st manually every time to get your phone to boot again. Or just stay on the 14/12/2020 build and everything works correctly.
Wait for them to fix their shitty mistake I guess :D

**Comment by drimulescu** [comment]
Thanks for your quick response.
I'm still a bit confused what is the best solution for my case because I don't want to lose my data and apps.
So from my understanding, the best thing to do is to flash via recovery the 14.12.2020 NikGapps over the current ones(hope this will not mess up my data) and after that, update your ROM via OTA and everything is OK.
The other solution might be to download your ROM and flash it manually(dirty flash) and then reflash the 31.12 Gapps again over it and it will work.
Are my assumptions correct?
Thank you

**Comment by synt4x93** [comment]
I was in your situation and this is what I did
Flashed 14/12/2020 nikgapps (over the top of the 31/12/2020 gapps with no wipes) boot to android then update via ota :) or flash in twrp.

Just keep a copy of the rom/14th gapps/magisk on your sdcard.
If anything goes wrong, format system in twrp and flash rom/gapps/magisk and reboot

**Comment by janvanveldhuizen** [comment]
I have TWRP installed, but not Magisk. Do I need to add that?
I will take the latest LineageOS18 from this repo anyway. Hope SeedVault will restore my apps...

**Comment by synt4x93** [comment]
If you don't need to use root then no, but it is useful to pass safetynet for banking apps etc, i'm using magisk v21.4
seedvault should work correctly, i've started using it recently and seems okay.

**Comment by janvanveldhuizen** [comment]
Ah yes, the banking apps. I already accepted that I need to do my banking activities on my laptop. Thanks.

**Comment by janvanveldhuizen** [comment]
Just one more question, just to be sure. When I already have TWRP, then I do not need to flash the recovery image, right?

**Comment by synt4x93** [comment]
The recovery images that i've uploaded are lineage recovery, not TWRP.. It is very simple compared to TWRP and not a lot of people like it as you can't easily do partition image backups etc to your sdcard directly from the phone. But i'm using it now and works very well.

TWRP works fine though so upto you, can easily switch between them.

**Comment by janvanveldhuizen** [comment]
By the way, any chance this repo will be the official version, eventually?

**Comment by synt4x93** [comment]
In the future yeah, it will be similar to this.. working on a better kernel for the official release, not rushing so may be a while.

**Comment by janvanveldhuizen** [comment]
Good. Don't feel pressed :-) I went back to the original firmware. Too much hassle with the bank apps.
Taking the bloatware for granted...

**Comment by synt4x93** [comment]
All my banking apps working okay here

**Comment by drimulescu** [comment]
Hello @synt4x93 
You know if the issue introduced in NikGapps from 31/12/2020 with the /system/addon.d script was fixed in their latest releases? Can we update from now on using the OTA system? Or do we have to flash the 14/12 gapps? 
Thank you

**Comment by synt4x93** [comment]
I tested their recent 30/01/2021 core package and fine, have not had chance to test 31 yet
