### ISSUE TITLE
Curious how long you think you will maintain this awesome custom ROM

### ISSUE THREAD

**Issue by isThatHim** [synt4x93/OTA#7]
Hi!
As the title states, i am curious for how long you think you likely will keep maintaining this ROM!

Thanks!

**Comment by synt4x93** [comment]
Will never die :p
I just got a new device but still own my note9, when I have some free time will start improving this some more since I have a second device now makes it easier.

But most likely I will only release OTA updates each month for security patches etc (unless big changes or vulnerabilities are found before that time comes)

**Comment by isThatHim** [comment]
Awesome to know and awesome work, thanks!

**Comment by runil** [comment]
Any updates coming this month? Thinking about switching to this from Android 10.
